Framework/Configuration/Settings.cs, HermesProxy/Auth/AuthClient.cs
This PR adds DNS resolution for both the Config and the Realmlist reply for the server.
- solves https://github.com/WowLegacyCore/HermesProxy/issues/9
=> Add DNS resolution

Framework/Logging/Log.cs
Make use of `BlockingCollection.GetConsumingEnumerable()` to get a "real time" logging system.
The previously used `Thread.Sleep(1);` waits for >16ms on windows which causes significant delays.
Especially skewed output from `DateTime.Now` if a lot of messages are logged.
=> Improved logging throughput

HermesProxy/World/Client/PacketHandlers/SpellHandler.cs, HermesProxy/World/Server/PacketHandlers/SpellHandler.cs, HermesProxy/World/Server/Packets/SpellPackets.cs
This PR improves the handling of totems created.
Now totems can be dismissed properly and when a new totem is created the correct `PLAYER_TOTEM_UPDATE` Event is fired, making the `GetTotemInfo` API available.
=> Improve Totem Handling

Framework/Logging/Log.cs, HermesProxy/Auth/AuthClient.cs, HermesProxy/World/Client/WorldClient.cs, HermesProxy/World/Server/WorldSocket.cs
Fix #46 
I don't know if this should be optional via config.
=> Added network direction in log

Framework/IO/ByteBuffer.cs, HermesProxy/BnetServer/Networking/Session.cs, HermesProxy/GlobalSessionData.cs, HermesProxy/World/Client/PacketHandlers/CharacterHandler.cs, HermesProxy/World/Enums/UnitDefines.cs, HermesProxy/World/Server/PacketHandlers/AccountDataHandler.cs, HermesProxy/World/Server/PacketHandlers/CharacterHandler.cs, HermesProxy/World/Server/Packets/AccountDataPackets.cs, HermesProxy/World/Server/Packets/CharacterPackets.cs
=> New handlers

Framework/Framework.csproj, HermesProxy/HermesProxy.csproj
Reverts WowLegacyCore/HermesProxy#64
=> Revert "Use dotnet 5 in project"

.gitignore, Framework/GameMath/EulerAngles.cs, Framework/GameMath/Quaternion.cs, Framework/Logging/Log.cs, HermesProxy/Auth/AuthClient.cs, HermesProxy/World/Client/PacketHandlers/ChatHandler.cs, HermesProxy/World/Client/PacketHandlers/UpdateHandler.cs, HermesProxy/World/Client/WorldClient.cs, HermesProxy/World/Server/WorldSocket.cs, README.md
=> Deeprun Tram fix

HermesProxy/GlobalSessionData.cs, HermesProxy/World/Client/PacketHandlers/ChatHandler.cs, HermesProxy/World/Client/PacketHandlers/QuestHandler.cs, HermesProxy/World/Client/PacketHandlers/UpdateHandler.cs, HermesProxy/World/Server/AccountDataManager.cs, HermesProxy/World/Server/CurrentPlayerStorage.cs, HermesProxy/World/Server/PacketHandlers/CharacterHandler.cs, HermesProxy/World/Server/PacketHandlers/GuildHandler.cs, HermesProxy/World/Server/Packets/GuildPackets.cs
=> Added auto decline guild invites

HermesProxy/World/Server/PacketHandlers/AuctionHandler.cs
=> Fix AH query when using inventory type

HermesProxy/World/Client/PacketHandlers/MiscHandler.cs
We somehow need to figure out what #51 causes, this prints a message in the in-game chat with some information.
=> Print a message to in-game chat when cropse query

HermesProxy/World/Client/PacketHandlers/UpdateHandler.cs
=> Fixed Zangarmarsh Elevator rotation

HermesProxy/World/Client/PacketHandlers/LootHandler.cs
=> Roll description fix

HermesProxy/Configuration/Settings.cs
=> Fixed config verification

HermesProxy/World/Client/PacketHandlers/MiscHandler.cs, HermesProxy/World/Client/PacketHandlers/UpdateHandler.cs, HermesProxy/World/Server/Packets/UpdatePackets.cs
Fixed #144 #51
Ref: #94 Issue 2
=> Fixed unable to resurrect bug

HermesProxy/Auth/AuthClient.cs, HermesProxy/Configuration/ConfigurationParser.cs, HermesProxy/Configuration/Settings.cs, HermesProxy/HermesProxy.config, HermesProxy/HermesProxy.csproj, HermesProxy/Program.cs, HermesProxy/Server.cs, HermesProxy/World/Server/AccountDataManager.cs
- Using System.CommandLine now
- When we are the owner of the window we delay the exit
=> New command line parser and default spell delay to ~30ms

HermesProxy/World/Server/PacketHandlers/ChatHandler.cs
The modern client supports more than 255 character long messages.
We split them on Hermes side so that GameServers don't kick the player
Fix #153
=> Split chat messages that are over 255 chars long

HermesProxy/CSV/Hotfix/ItemEffect1.csv, HermesProxy/CSV/Hotfix/ItemEffect2.csv, HermesProxy/World/Client/WorldClient.cs, HermesProxy/World/GameData.cs, HermesProxy/World/Server/PacketHandlers/SpellHandler.cs, HermesProxy/World/Server/WorldSocket.cs
=> Added ItemEffect hotfixes

HermesProxy/World/Client/PacketHandlers/GroupHandler.cs, HermesProxy/World/Enums/GroupDefines.cs
=> Fixed invite to group responses

HermesProxy/GlobalSessionData.cs, HermesProxy/World/Client/PacketHandlers/TradeHandler.cs, HermesProxy/World/Server/PacketHandlers/SpellHandler.cs, HermesProxy/World/Server/PacketHandlers/TradeHandler.cs
=> Allow enchants and lockbox unlocking in trade

HermesProxy/GlobalSessionData.cs, HermesProxy/World/Client/PacketHandlers/GroupHandler.cs, HermesProxy/World/Server/PacketHandlers/GroupHandler.cs
=> Send kick message when kicked from group

HermesProxy/World/GameData.cs, HermesProxy/World/Server/Packets/UpdatePackets.cs
=> Fixed unknown faction for corpses (fix unable to rezz corpse)

HermesProxy/World/Client/PacketHandlers/UpdateHandler.cs
=> Fixed size to scale ratio

HermesProxy/World/Client/PacketHandlers/GroupHandler.cs
=> Fixed vanilla group kick response

HermesProxy/Configuration/Settings.cs, HermesProxy/HermesProxy.config, HermesProxy/Server.cs, HermesProxy/VersionChecker.cs, HermesProxy/World/Client/PacketHandlers/ChatHandler.cs
- Auto select `ServerBuild` based on `ClientBuild`
- Print Client/Server Build + ExternalIP at start
- Don't remote at ourselves when targeting an NPC #215
=> General Improvements

HermesProxy/GlobalSessionData.cs, HermesProxy/World/Client/PacketHandlers/ChatHandler.cs, HermesProxy/World/Client/PacketHandlers/SocialHandler.cs, HermesProxy/World/Client/WorldClient.cs
=> Fix player chat ignores

Framework/IO/ByteBuffer.cs, HermesProxy/BnetServer/Services/BnetServices.cs, HermesProxy/BnetServer/Services/Services/GameUtilities.cs, HermesProxy/GlobalSessionData.cs, HermesProxy/World/Client/PacketHandlers/GroupHandler.cs, HermesProxy/World/Client/PacketHandlers/QueryHandler.cs, HermesProxy/World/Client/PacketHandlers/SupportTicketHandler.cs, HermesProxy/World/Enums/SupportTicketDefines.cs, HermesProxy/World/Server/AccountDataManager.cs, HermesProxy/World/Server/PacketHandlers/SupportTicketHandler.cs, HermesProxy/World/Server/Packets/SupportTicketPackets.cs, HermesProxy/World/Server/WorldSocket.cs, HermesProxy/World/WowGuid.cs
- Prevent users from stucking in disconnect loop if WorldServer is offline
- Improved quick-report feature
=> Improvements

HermesProxy/World/Client/PacketHandlers/UpdateHandler.cs
Original: https://github.com/WowLegacyCore/HermesProxy/pull/310
Fixes #212
=> Fix player freeze issue with 'Eyes of the Beast'

HermesProxy/World/Client/PacketHandlers/QuestHandler.cs, HermesProxy/World/Client/WorldClient.cs, HermesProxy/World/Enums/QuestDefines.cs, HermesProxy/World/Server/Packets/AuthenticationPackets.cs, HermesProxy/World/Server/WorldSocket.cs
Fixes https://github.com/WowLegacyCore/HermesProxy/issues/267
=> Ratkosrb merge5

HermesProxy/World/Client/PacketHandlers/ChatHandler.cs, HermesProxy/World/Client/PacketHandlers/UpdateHandler.cs, HermesProxy/World/Server/CurrentPlayerStorage.cs
=> Fix quest complete flag when changing map
